name: LeetCode Synchronizer

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Run LeetCode Synchronizer
        uses: paul-dev-28/LeetSync@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
